### ISSUE TITLE
[Issue]: KFDIPCTest.BasicTest failed on 7900XT

### ISSUE THREAD

**Issue by littlewu2508** [ROCm/ROCT-Thunk-Interface#103]
### Problem Description

When disabling iGPU, KFDIPCTest.BasicTest failed on 7900XT:
```
/fast/portage/dev-libs/roct-thunk-interface-6.1.0/work/ROCT-Thunk-Interface-rocm-6.1.0/tests/kfdtest/src/KFDIPCTest.cpp:145: Failure
Value of: (hsaKmtShareMemory(toShareLocalBuffer, size, &sharedHandleLM))
  Actual: 1
Expected: HSAKMT_STATUS_SUCCESS
Which is: 0
[  FAILED  ] KFDIPCTest.BasicTest (43 ms)
[----------] 1 test from KFDIPCTest (43 ms total)
```

Full build an test log: 
[build.log.gz](https://github.com/ROCm/ROCT-Thunk-Interface/files/15185857/build.log.gz)

Also, during tests there's a GPU reset event, not sure if it is triggered by this test (because when I rerun this test, there's no GPU reset):

```
[May 1 15:07] gmc_v11_0_process_interrupt: 29 callbacks suppressed
[  +0.000003] amdgpu 0000:03:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:40 vmid:8 pasid:32772, for process kfdtest pid 10739 thread kfdtest pid 10739)
[  +0.000023] amdgpu 0000:03:00.0: amdgpu:   in page starting at address 0x0000000012345000 from client 10
[  +0.000955] amdgpu 0000:03:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x00841050
[  +0.000754] amdgpu 0000:03:00.0: amdgpu:       Faulty UTCL2 client ID: TCP (0x8)
[  +0.000713] amdgpu 0000:03:00.0: amdgpu:       MORE_FAULTS: 0x0
[  +0.000684] amdgpu 0000:03:00.0: amdgpu:       WALKER_ERROR: 0x0
[  +0.000652] amdgpu 0000:03:00.0: amdgpu:       PERMISSION_FAULTS: 0x5
[  +0.000646] amdgpu 0000:03:00.0: amdgpu:       MAPPING_ERROR: 0x0
[  +0.000642] amdgpu 0000:03:00.0: amdgpu:       RW: 0x1
[  +0.000938] amdgpu: sq_intr: error, detail 0x00000000, type 2, sh 0, priv 1, wave_id 0, simd_id 0, wgp_id 0
...
```

[dmesg.log.gz](https://github.com/ROCm/ROCT-Thunk-Interface/files/15185889/dmesg.log.gz)

When enabling the gfx1036 iGPU of Ryzen 7700, there are more test failures, and kfdtest hangs at `KFDSVMRangeTest.MigratePolicyTest`. Full log: 
[build.log.gz](https://github.com/ROCm/ROCT-Thunk-Interface/files/15185911/build.log.gz)

### Operating System

Gentoo Prefix on kernel 6.7.9

### CPU

AMD Ryzen 7 7700 8-Core Processor

### GPU

AMD Radeon RX 7900 XT

### ROCm Version

ROCm 6.1.0

### ROCm Component

ROCT-Thunk-Interface

### Steps to Reproduce

Start from Gentoo amd64 stage3 tarball, In root shell
```bash
## Setup ebuild repo, currently in my own branch
pushd /var/db/repos
rm -rf gentoo
git clone --depth 1 https://github.com/littlewu2508/gentoo.git -b rocm-runtime-6.1

## Testing setup
usermod –a –G render portage # add portage to render group to access GPU
mkdir -p /etc/portage/env/
echo 'FEATURES="test"' > /etc/portage/env/test.conf
echo 'dev-libs/roct-thunk-interface test.conf' > /etc/portage/package.env

## Install deps and execute test
emerge -v "=dev-libs/roct-thunk-interface-6.1.0"
```

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

[rocminfo.txt](https://github.com/ROCm/ROCT-Thunk-Interface/files/15185923/rocminfo.txt)

### Additional Information

The system use Linux 6.7.9 upstream kernel with its amdgpu/amdkfd driver, not ROCm-6.1 dkms module

**Comment by littlewu2508** [comment]
I updated to version ROCm-6.1.1 and the failure still exists

**Comment by kentrussell** [comment]
KFDtest's IPC test uses the IPC implementation supported by amdgpu-dkms, which is not upstreamable (and thus won't work with a non-amdgpu-dkms kernel). It needs to be rewritten to utilize the DMABuf-based IPC that was recently added to ROCm. This is expected when using an upstream kernel.
