### ISSUE TITLE
[Issue]: Outdated license for kfdtest

### ISSUE THREAD

**Issue by trixirt** [ROCm/ROCT-Thunk-Interface#109]
### Problem Description

Requesting a license review for
[LICENSE.kfdtest](https://github.com/ROCm/ROCT-Thunk-Interface/blob/master/tests/kfdtest/LICENSE.kfdtest)

libamdsp3 - AMD SP3 shader assembler library LICENSE
/* The following license applies to the SP3 shader assembler, which is
 * named as libamdsp3.a and will be built into the kfdtest binary.
 */

Looks the files for sp3/ were removed around rocm-5.2.x to rocm-5.3.x

### Operating System

Fedora

### CPU

Threadripper

### GPU

AMD Radeon Pro W7900

### ROCm Version

ROCm 6.2.0

**Comment by cgmb** [comment]
The dependency on libamdsp3.a was removed in the ROCm 5.x era and the comment has been obsolete for some time. The comment been dropped in the consolidated rocr-runtime repository with https://github.com/ROCm/ROCR-Runtime/commit/c574c818353eeb56f34c84a50932b61b9b028eb1.
