### ISSUE TITLE
Mismatch between project version and SOVERSION

### ISSUE THREAD

**Issue by rigtorp** [ROCm/ROCT-Thunk-Interface#62]
Project version is defined in CMakeLists.txt:
```
project ( ${HSAKMT_TARGET} VERSION 1.9.0)
```

But later it's not used for the library version (VERSION and SOVERSION):
```
set ( LIB_VERSION_MAJOR 1)
set ( LIB_VERSION_MINOR 0)
if (${ROCM_PATCH_VERSION})
    set ( LIB_VERSION_PATCH ${ROCM_PATCH_VERSION} )
else ()
    set ( LIB_VERSION_PATCH 6)
endif ()
```
Instead the `CMAKE_PROJECT_VERSION`,  `CMAKE_PROJECT_VERSION_MAJOR`, etc variables can be used: https://cmake.org/cmake/help/latest/variable/CMAKE_PROJECT_VERSION.html

Additionally these version numbers do not change between releases. What version should be used when packaging? Fedora for example uses *1.0.6*: https://src.fedoraproject.org/rpms/hsakmt/blob/master/f/hsakmt.spec

**Comment by ppanchad-amd** [comment]
@rigtorp Apologies for the lack of response. Can you please check if your issue still exists with the latest ROCm 6.1.3? If not, please close the ticket. Thanks!

**Comment by kentrussell** [comment]
We've moved to using a static thunk, so this isn't being actively supported. Thanks for your inquiry.
