### ISSUE TITLE
Test drv does not compile

### ISSUE THREAD

**Issue by Maxzor** [ROCm/ROCT-Thunk-Interface#71]
roct-thunk-interface/tests/rdma/simple/drv
I cannot find a definition for `amd_p2p_page_table`

**Comment by ppanchad-amd** [comment]
@Maxzor Apologies for the lack of response.  Please check with the latest ROCm 6.1.3.  If issue is resolved, please close the ticket. Thanks!

**Comment by kentrussell** [comment]
Philip got this test working again. Please reopen the issue if it's still happening in 6.1.3 or later.
