### ISSUE TITLE
Repository branch layout is confusing and not inclusively named

### ISSUE THREAD

**Issue by aaronmondal** [ROCm/ROCT-Thunk-Interface#82]
Regarding the layout of this repository:

- The `rocm-5.4.3` tag is ahead of `master` and the `dev` branch has been unused since 2016.
- The [branch overview](https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/branches) also doesn't make it obvious that the latest `rocm-5.4.3` is actually a few commits ahead of `master`.
- The primary development branch being named `master` instead of `main` or `trunk` goes against inclusiveness best practices.

Potential fixes:

- Rename `master` to `main`.
- Remove unused non-release branches like `dev` to avoid confusion.
- Put all new commits on main and branch releases off of main. I think this is already the case at the moment. However, to make sure that main is always the "latest" code, commit all changes to `main` and then explicitly backport/cherrypick those commits into the release branches if post-release bugfixes are needed. I.e. don't allow manual commits onto release branches after they have been cut. This approach is used e.g. by the llvm-project repository.

**Comment by kentrussell** [comment]
Thanks for the comment. This is something that I am working on with the Infrastructure team. Previously I was manually updating the project myself, but it's a simple process so it's been automated. However the master branch was missed for this and other projects, so I am working with our internal Infra team to ensure that master is always aligned with the latest release.

**Comment by kentrussell** [comment]
Just updating here, we're merging thunk into ROCr soon, so the release and branching will be more sane. Including updating a dev-type branch more than once a decade
